variable "app" {}
variable "env" {}
variable "account_id" {}
variable "region" {}
variable "vpc_id" {}
variable "subnet_ids" {}
variable "web_container_name" {}
variable "ecs_sg_id" {}
variable "ecs_task_execution_role_arn" {}
variable "cloudwatch_log_group_for_ecs" {}
variable "target_group_arn" {}